GET https://amcortradingbot.herokuapp.com/api

###

GET http://localhost:7000/api/

###
GET http://localhost:7000/api/transactions/generate-addressc

###
GET http://localhost:7000/api/auth/users-account

###
POST http://localhost:7000/api/auth/register
Content-Type: application/json

{
    "username": "emmanuella"
}

###
POST http://localhost:7000/api/transactions/deposit
Content-Type: application/json

{
    "username": "emmanuella",
    "amount": "5000"
}
###
POST http://localhost:7000/api/transactions/invest
Content-Type: application/json

{
    "username": "Henry",
    "amount": "2200"
}
###
POST http://localhost:7000/api/transactions/withdrawal
Content-Type: application/json

{
    "username": "Emmanuel",
    "amount": "5000"
}

###
GET http://localhost:7000/api/transactions/balance
Content-Type: application/json

{
    "username": "Emmanuel"
}

###
POST http://localhost:7000/api/auth/register-admin
Content-Type: application/json

{
    "firstname": "Emmanuel",
    "lastname": "Obioma",
    "phone": "081635437035",
    "password": "urbskv ",
    "email": "emmanuelchinazfad5777@gmail.com"
}

###

POST https://api.cryptoapis.io/v1/bc/btc/mainnet/address
Content-Type: application/json
X-API-Key: 861b1e252e3d996974fdc4f8e9b0e8b6ee7171f3


###
GET https://amcortradingbot.herokuapp.com/api/transactions/generate-address
Content-Type: application/json

