GET http://localhost:5000/api/auth/users-account

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Henry"
}

###
POST http://localhost:5000/api/transactions/deposit
Content-Type: application/json

{
    "username": "Emmanuel",
    "amount": "5000"
}
###
POST http://localhost:5000/api/transactions/invest
Content-Type: application/json

{
    "username": "Henry",
    "amount": "2200"
}
###
POST http://localhost:5000/api/transactions/withdrawal
Content-Type: application/json

{
    "username": "Emmanuel",
    "amount": "5000"
}